### ISSUE TITLE
Infer MultiPolygon structure from winding order for toGeoJSON

### ISSUE THREAD

**Issue by mourner** [mapbox/vector-tile-js#32]
MultiPolygons are flattened in VT, so we need to infer their structure from winding order like this https://github.com/mapbox/mapbox-gl-js/blob/earcut-final/js/util/classify_rings.js, otherwise MultiPolygons are broken (encoded as Polygons, with additional outer rings becoming holes). cc @jfirebaugh

**Comment by jfirebaugh** [comment]
How about changing `loadGeometry()` instead? We could have it do classification if `type == 3`, and use one more level of array nesting. This would require a major version change for vector-tile-js, but would allow us to remove `classify_rings.js` from gl-js, rather than duplicating it in both modules.

**Comment by mourner** [comment]
@jfirebaugh sounds good to me!

**Comment by jfirebaugh** [comment]
⇢ #33
