### ISSUE TITLE
Why can't I read the tile in tiles.getTile() of mbtiles?

### ISSUE THREAD

**Issue by Phlicess** [mapbox/vector-tile-js#50]
Hello,  I used the tippecanoe to build a mbtiles file, but I can't use vector-tile-js parse the tile with tiles.getTile() .  It likes follow:

```

  tiles.getTile(p.z, p.x, p.y, function (err, tile, headers) {
                if (err) {
                    res.end();
                } else {
                    res.writeHead(200, headers);
                    console.log(tile);

                    var vectorTileContent = new VectorTile(new Pbf(tile));
                    var orig = vectorTileContent.layers['xzqgeojson'].feature(0).toGeoJSON(0, 0, 1);
                }
    }) 
```

I want to edit the pbf of mbtils after I parse the pbf to geojson and to save the edited pbf to the mbtils.  Could you please tell me what I should to do?
    Thanks!

**Comment by jfirebaugh** [comment]
Hi @Phlicess -- we'd need more information in order to help you here. Specifically, when you say "I can't use vector-tile-js", what do you mean? Did you not get the output you expected, was there an error, etc? Or, if you can provide a minimal, self-contained example project that demonstrates the issue, that is an excellent way to make a high-quality bug report.

Closing here, because I don't think we're going to be able to diagnose this from the information we have.
